import { TournamentEdgeScan, EdgeOpportunity } from '@/types';

/**
 * Generate demo data for testing the UI before API keys are connected
 */
export function getDemoScan(): TournamentEdgeScan {
  const demoEdges: EdgeOpportunity[] = [
    {
      id: 'demo-1',
      player_name: 'Scottie Scheffler',
      player_id: 18417,
      market_type: 'top_20',
      market_label: 'Top 20',
      model_prob: 82.3,
      market_prob: 74.0,
      edge: 8.3,
      edge_pct: 11.2,
      kelly_fraction: 0.0892,
      half_kelly: 0.0446,
      quarter_kelly: 0.0223,
      contract_price: 74,
      payout: 100,
      expected_value: 8.3,
      volume: 347,
      open_interest: 218,
      liquidity_grade: 'A',
      tier: 'strong',
      is_live: false,
      timestamp: new Date().toISOString(),
    },
    {
      id: 'demo-2',
      player_name: 'Rory McIlroy',
      player_id: 14849,
      market_type: 'win',
      market_label: 'Outright Win',
      model_prob: 9.8,
      market_prob: 6.0,
      edge: 3.8,
      edge_pct: 63.3,
      kelly_fraction: 0.0362,
      half_kelly: 0.0181,
      quarter_kelly: 0.0091,
      contract_price: 6,
      payout: 100,
      expected_value: 3.8,
      volume: 523,
      open_interest: 340,
      liquidity_grade: 'A',
      tier: 'playable',
      is_live: false,
      timestamp: new Date().toISOString(),
    },
    {
      id: 'demo-3',
      player_name: 'Collin Morikawa',
      player_id: 20098,
      market_type: 'top_10',
      market_label: 'Top 10',
      model_prob: 38.5,
      market_prob: 31.0,
      edge: 7.5,
      edge_pct: 24.2,
      kelly_fraction: 0.0714,
      half_kelly: 0.0357,
      quarter_kelly: 0.0179,
      contract_price: 31,
      payout: 100,
      expected_value: 7.5,
      volume: 189,
      open_interest: 95,
      liquidity_grade: 'B',
      tier: 'strong',
      is_live: false,
      timestamp: new Date().toISOString(),
    },
    {
      id: 'demo-4',
      player_name: 'Tommy Fleetwood',
      player_id: 15503,
      market_type: 'top_20',
      market_label: 'Top 20',
      model_prob: 52.1,
      market_prob: 45.0,
      edge: 7.1,
      edge_pct: 15.8,
      kelly_fraction: 0.0632,
      half_kelly: 0.0316,
      quarter_kelly: 0.0158,
      contract_price: 45,
      payout: 100,
      expected_value: 7.1,
      volume: 76,
      open_interest: 42,
      liquidity_grade: 'B',
      tier: 'strong',
      is_live: false,
      timestamp: new Date().toISOString(),
    },
    {
      id: 'demo-5',
      player_name: 'Xander Schauffele',
      player_id: 17897,
      market_type: 'top_5',
      market_label: 'Top 5',
      model_prob: 28.4,
      market_prob: 24.0,
      edge: 4.4,
      edge_pct: 18.3,
      kelly_fraction: 0.0345,
      half_kelly: 0.0173,
      quarter_kelly: 0.0086,
      contract_price: 24,
      payout: 100,
      expected_value: 4.4,
      volume: 294,
      open_interest: 167,
      liquidity_grade: 'A',
      tier: 'playable',
      is_live: false,
      timestamp: new Date().toISOString(),
    },
    {
      id: 'demo-6',
      player_name: 'Viktor Hovland',
      player_id: 20098,
      market_type: 'win',
      market_label: 'Outright Win',
      model_prob: 6.2,
      market_prob: 3.5,
      edge: 2.7,
      edge_pct: 77.1,
      kelly_fraction: 0.0243,
      half_kelly: 0.0122,
      quarter_kelly: 0.0061,
      contract_price: 4,
      payout: 100,
      expected_value: 2.2,
      volume: 134,
      open_interest: 89,
      liquidity_grade: 'B',
      tier: 'monitor',
      is_live: false,
      timestamp: new Date().toISOString(),
    },
  ];

  return {
    tournament: 'Arnold Palmer Invitational (DEMO)',
    course: 'Bay Hill Club & Lodge',
    scan_time: new Date().toISOString(),
    is_live: false,
    model_type: 'baseline_history_fit',
    edges: demoEdges,
    strong_count: demoEdges.filter(e => e.tier === 'strong').length,
    playable_count: demoEdges.filter(e => e.tier === 'playable').length,
    total_scanned: 156,
  };
}
